#!/usr/bin/env bash 


echo  "Please enter email address to check against pasteaccount"

read choice
response=$(curl --write-out %{http_code} --silent --output /dev/null "https://haveibeenpwned.com/api/v2/pasteaccount/$choice")

if [ "$response" = "404" ];then
    echo "Congralaution!!You are safe "

elif [ "$response" = "400" ];then
    echo "Upps.Something went wrong." 
 
  
else
    echo  "We got paste "
	curl --silent --request GET "https://haveibeenpwned.com/api/v2/pasteaccount/$choice"|python -mjson.tool > $choice.txt
	cat $choice.txt|sed -e 's!http\(s\)\{0,1\}://[^[:space:]]*!!g' -e 's/[@#\$%^&*()=039"]//g' -e 's/<\/td>//g' -e 's/<em>//g' -e 's/<\/em>//g' -e 's/<a//g'  -e 's/<\/a>//g'  >  Breach_$choice.txt
	#cat Breach_$choice.txt
	rm $choice.txt
	
	cat Breach_$choice.txt| grep Id: | awk '{print substr($0,13)}' | tr -dc '[:alnum:]\n\r' > temp1
	cat temp1 | while read f1	
  	do
	  	echo "Found URL :: http://pastebin.com/"$f1""
  	done
	rm temp1
	echo "Output saved it into Breach_$choice.txt file"

fi
